### ISSUE TITLE
Understand initializeFCM() function fully

### ISSUE THREAD

**Issue by chiraganand** [StorySurf/t_app#2]
https://github.com/StorySurf/t_app/blob/f0510d5fa066e074b840e3078ddd70740ede30b7/lib/main.dart#L96

**Comment by rohansamanta** [comment]
Yes, so the `initializeFCM()` function does three things currently - 

1. `configure` as the name suggests configures message handlers for the app -   
   - `onMessage` : This callback function would be called when the app is running in the foreground. And will work as per 
                            definition inside the configure() function.
   - `onResume` : This callback function would be called if the app is in the background but running. Rest will do as definition.
   - `onLaunch` : This is for when the app is terminated and needs to reboot.
   
   These three function will be called automatically in case of their respective use cases by firebase messaging.
2.`requestNotificationPermissions` Asks for permissions in case of iOS devices. 
3. The `onIosSettingsRegistered` will check for changes in notification permissions by users (only for iOS devices)
4. `getToken()` : This returns the firebase token and prints it in the console.
